requirements-docs.txt: add urllib3~=1.26.15
workaround for:
exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the
'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'

Issue-ID: INF-428

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>
Change-Id: Iaa54727b525cc0038f8cf46991c9431a237480ba
(cherry picked from commit 1d5a75e98937f6ede6fe3bfeedf6fd868b80fd33)