stx-puppet: add re-tries to workaround docker login failure
Add re-tries to workaround the follwoing docker login failure:
Error: docker login registry.local:9001 -u admin -p St8rlingX* returned 1 instead of one of [0]
Error: /Stage[main]/Platform::Kubernetes::Master::Init/Exec[login local
       registry]/returns: change from notrun to 0 failed: docker login
       registry.local:9001 -u admin -p St8rlingX* returned 1 instead of one of [0]

Issue-ID: INF-204
Signed-off-by: Jackie Huang <jackie.huang@windriver.com>
Change-Id: I7087b8b5e27baa617bebbada0a09953299829432